### ISSUE TITLE
A way to patch only codec?

### ISSUE THREAD

**Issue by narcisgarcia** [traud/asterisk-alaw16#1]
Is there a way to not have to path and build whole Asterisk 13?
I've tried proposed procedure in an already installed Asterisk 13 on Debian 9 (from repositories); it builds and installs a new Asterisk 13 and it's not starting

```
Jul 31 09:56:50 hostname systemd[1]: asterisk.service: Start operation timed out. Terminating.
Jul 31 09:56:50 hostname asterisk[22230]: 
Jul 31 09:56:50 hostname systemd[1]: Failed to start Asterisk PBX.
Jul 31 09:56:50 hostname systemd[1]: asterisk.service: Unit entered failed state.
Jul 31 09:56:50 hostname systemd[1]: asterisk.service: Failed with result 'timeout'.
```

**Comment by traud** [comment]
Puh. Good question. I am not sure if that is possible because of the format cache. Anyway, Debian provides no security updates for Asterisk. Therefore, I do not support the pre-build packages of Debian. My Read Me contains steps for Ubuntu. Those should do on Debian. Any issues with those?

**Comment by narcisgarcia** [comment]
issue (apart of not starting at first) is to not be able to use codecs from Debian repositories and other files/packages mixing problems.

At asterisk.hosting.lv is provided G.729 FOSS codec as a single "codec_g729.so" file to be placed at /usr/lib/asterisk/modules/ and works in Debian's Asterisk 13.
Couldn't be done same way for "codec_alaw16.so" ?

**Comment by traud** [comment]
That cannot be compared because those modules ‘just’ add transcoding. Asterisk already supported pass-through for those media codecs. The module which can be compared best is Digium SiLK because that adds both pass-through and transcoding. However, even for that module, code pieces are within Asterisk (format cache). So the question is, whether this can be added dynamically as well or whether a media module works without that. I have not looked into that.

> issue (apart of not starting at first) is to not be able to use codecs from Debian repositories and other files/packages mixing problems.

Can you give a bit more detail on that? As stated, that is the path you should go (for my module and for security in general). Perhaps I can help with that. By the way, for what reason do you need this module? It is experimental and should be used only for testing/interoperability purposes.

**Comment by narcisgarcia** [comment]
Okay, I didn't know this module is experimental.
The rest of packages I've installed from Debian repositories are stable enough to not worry about each issue with each recompiled file: this is the reason to try to avoid installing recompiled Asterisk at all, for only one module.

**Comment by traud** [comment]
OK, then I am closing this issue. This module is only for interoperability testing, for example if you are a VoIP/SIP provider and you want to test your gateways. If you have or find another use case, which requires this module, please, re-open this issue again. Then, I might have a look at a solution.

Just to re-amphazize, the packages from Debian do not see security updates. If you are using Asterisk as server, publicly available on the Internet, you have to find a way to use the latest source. If you like the patches of Debian, you can re-compile Asterisk with that. If you fail to mention your issues with those sources, nobody is able to help you to fix those issues.
